Update apk.yml

diff --git a/.github/workflows/apk.yml b/.github/workflows/apk.yml
--- a/.github/workflows/apk.yml
+++ b/.github/workflows/apk.yml
@@ -15,16 +15,22 @@ jobs:
           distribution: 'temurin'
           java-version: '17'
 
-      - name: Make Gradle Executable
-        run: chmod +x mobile/android/gradlew
-        working-directory: .
-
-      - name: Build Debug APK
-        run: ./gradlew assembleDebug
-        working-directory: mobile/android
+      - name: Find and Build APK
+        run: |
+          GRADLE_PATH=$(find . -name "gradlew" -type f | head -n 1)
+          if [ -z "$GRADLE_PATH" ]; then
+            echo "Error: gradlew file not found!"
+            exit 1
+          fi
+          PROJECT_DIR=$(dirname "$GRADLE_PATH")
+          echo "Found project at: $PROJECT_DIR"
+          
+          cd "$PROJECT_DIR"
+          chmod +x gradlew
+          ./gradlew assembleDebug
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: app-debug
-          path: mobile/android/app/build/outputs/apk/debug/app-debug.apk
+          path: '**/app/build/outputs/apk/debug/app-debug.apk'
